name: Boxcar for unRAID
markdown: redcarpet
pygments: true

permalink: /news/:year/:month/:day/:title/
exclude: [
	'sass',
	'Gemfile*',
	'README.md'
]

boxcar_installer: bash <(curl -s http://boxcar.nicinabox.com/install)
curl_installer: wget -qO- http://boxcar.nicinabox.com/install_curl | sh -
