#!/usr/bin/bash
#
# Install:
# wget -qO- http://nicinabox.com/boxcar/install_curl | sh -
#

url='http://slackware.cs.utah.edu/pub/slackware/slackware-13.1/slackware/n/curl-7.20.1-i486-1.txz'
package=`basename $url`

mkdir -p /boot/extra && cd $_

wget -q $url
installpkg $package
